import React from "react";
import { Section } from "../../../styles/card/produtoStyles/produtoStyleCard";
import { CardProduto } from "./components/card";
import logo from "../../../assets/starpet.png"

export function Produto({src}){
    return(
        <Section>
           <CardProduto src={logo} nome={"Raçao para cachorro aldfjalsjflajdflakjdflajalfjaljfladjflakfjalkfjlalsfjklafjlajfaljdflajdflakjlkfdjalkjf"} preco={"R$"+15.5} />
           <CardProduto src={logo} nome={"Raçao para cachorro aldfjalsjflajdflakjdflajalfjaljfladjflakfjalkfjlalsfjklafjlajfaljdflajdflakjlkfdjalkjf"} preco={"R$"+15.5} /><CardProduto src={logo} nome={"Raçao para cachorro aldfjalsjflajdflakjdflajalfjaljfladjflakfjalkfjlalsfjklafjlajfaljdflajdflakjlkfdjalkjf"} preco={"R$"+15.5} /><CardProduto src={logo} nome={"Raçao para cachorro aldfjalsjflajdflakjdflajalfjaljfladjflakfjalkfjlalsfjklafjlajfaljdflajdflakjlkfdjalkjf"} preco={"R$"+15.5} /><CardProduto src={logo} nome={"Raçao para cachorro aldfjalsjflajdflakjdflajalfjaljfladjflakfjalkfjlalsfjklafjlajfaljdflajdflakjlkfdjalkjf"} preco={"R$"+15.5} />
           <CardProduto src={logo} nome={"Raçao para cachorro aldfjalsjflajdflakjdflajalfjaljfladjflakfjalkfjlalsfjklafjlajfaljdflajdflakjlkfdjalkjf"} preco={"R$"+15.5} /><CardProduto src={logo} nome={"Raçao para cachorro aldfjalsjflajdflakjdflajalfjaljfladjflakfjalkfjlalsfjklafjlajfaljdflajdflakjlkfdjalkjf"} preco={"R$"+15.5} /><CardProduto src={logo} nome={"Raçao para cachorro aldfjalsjflajdflakjdflajalfjaljfladjflakfjalkfjlalsfjklafjlajfaljdflajdflakjlkfdjalkjf"} preco={"R$"+15.5} /><CardProduto src={logo} nome={"Raçao para cachorro aldfjalsjflajdflakjdflajalfjaljfladjflakfjalkfjlalsfjklafjlajfaljdflajdflakjlkfdjalkjf"} preco={"R$"+15.5} />
           <CardProduto src={logo} nome={"Raçao para cachorro aldfjalsjflajdflakjdflajalfjaljfladjflakfjalkfjlalsfjklafjlajfaljdflajdflakjlkfdjalkjf"} preco={"R$"+15.5} /><CardProduto src={logo} nome={"Raçao para cachorro aldfjalsjflajdflakjdflajalfjaljfladjflakfjalkfjlalsfjklafjlajfaljdflajdflakjlkfdjalkjf"} preco={"R$"+15.5} /><CardProduto src={logo} nome={"Raçao para cachorro aldfjalsjflajdflakjdflajalfjaljfladjflakfjalkfjlalsfjklafjlajfaljdflajdflakjlkfdjalkjf"} preco={"R$"+15.5} /><CardProduto src={logo} nome={"Raçao para cachorro aldfjalsjflajdflakjdflajalfjaljfladjflakfjalkfjlalsfjklafjlajfaljdflajdflakjlkfdjalkjf"} preco={"R$"+15.5} />
           <CardProduto src={logo} nome={"Raçao para cachorro aldfjalsjflajdflakjdflajalfjaljfladjflakfjalkfjlalsfjklafjlajfaljdflajdflakjlkfdjalkjf"} preco={"R$"+15.5} /><CardProduto src={logo} nome={"Raçao para cachorro aldfjalsjflajdflakjdflajalfjaljfladjflakfjalkfjlalsfjklafjlajfaljdflajdflakjlkfdjalkjf"} preco={"R$"+15.5} /><CardProduto src={logo} nome={"Raçao para cachorro aldfjalsjflajdflakjdflajalfjaljfladjflakfjalkfjlalsfjklafjlajfaljdflajdflakjlkfdjalkjf"} preco={"R$"+15.5} /><CardProduto src={logo} nome={"Raçao para cachorro aldfjalsjflajdflakjdflajalfjaljfladjflakfjalkfjlalsfjklafjlajfaljdflajdflakjlkfdjalkjf"} preco={"R$"+15.5} />
           <CardProduto src={logo} nome={"Raçao para cachorro aldfjalsjflajdflakjdflajalfjaljfladjflakfjalkfjlalsfjklafjlajfaljdflajdflakjlkfdjalkjf"} preco={"R$"+15.5} /><CardProduto src={logo} nome={"Raçao para cachorro aldfjalsjflajdflakjdflajalfjaljfladjflakfjalkfjlalsfjklafjlajfaljdflajdflakjlkfdjalkjf"} preco={"R$"+15.5} /><CardProduto src={logo} nome={"Raçao para cachorro aldfjalsjflajdflakjdflajalfjaljfladjflakfjalkfjlalsfjklafjlajfaljdflajdflakjlkfdjalkjf"} preco={"R$"+15.5} /><CardProduto src={logo} nome={"Raçao para cachorro aldfjalsjflajdflakjdflajalfjaljfladjflakfjalkfjlalsfjklafjlajfaljdflajdflakjlkfdjalkjf"} preco={"R$"+15.5} />
           <CardProduto src={logo} nome={"Raçao para cachorro aldfjalsjflajdflakjdflajalfjaljfladjflakfjalkfjlalsfjklafjlajfaljdflajdflakjlkfdjalkjf"} preco={"R$"+15.5} /><CardProduto src={logo} nome={"Raçao para cachorro aldfjalsjflajdflakjdflajalfjaljfladjflakfjalkfjlalsfjklafjlajfaljdflajdflakjlkfdjalkjf"} preco={"R$"+15.5} /><CardProduto src={logo} nome={"Raçao para cachorro aldfjalsjflajdflakjdflajalfjaljfladjflakfjalkfjlalsfjklafjlajfaljdflajdflakjlkfdjalkjf"} preco={"R$"+15.5} /><CardProduto src={logo} nome={"Raçao para cachorro aldfjalsjflajdflakjdflajalfjaljfladjflakfjalkfjlalsfjklafjlajfaljdflajdflakjlkfdjalkjf"} preco={"R$"+15.5} />
           <CardProduto src={logo} nome={"Raçao para cachorro aldfjalsjflajdflakjdflajalfjaljfladjflakfjalkfjlalsfjklafjlajfaljdflajdflakjlkfdjalkjf"} preco={"R$"+15.5} /><CardProduto src={logo} nome={"Raçao para cachorro aldfjalsjflajdflakjdflajalfjaljfladjflakfjalkfjlalsfjklafjlajfaljdflajdflakjlkfdjalkjf"} preco={"R$"+15.5} /><CardProduto src={logo} nome={"Raçao para cachorro aldfjalsjflajdflakjdflajalfjaljfladjflakfjalkfjlalsfjklafjlajfaljdflajdflakjlkfdjalkjf"} preco={"R$"+15.5} /><CardProduto src={logo} nome={"Raçao para cachorro aldfjalsjflajdflakjdflajalfjaljfladjflakfjalkfjlalsfjklafjlajfaljdflajdflakjlkfdjalkjf"} preco={"R$"+15.5} />
           <CardProduto src={logo} nome={"Raçao para cachorro aldfjalsjflajdflakjdflajalfjaljfladjflakfjalkfjlalsfjklafjlajfaljdflajdflakjlkfdjalkjf"} preco={"R$"+15.5} /><CardProduto src={logo} nome={"Raçao para cachorro aldfjalsjflajdflakjdflajalfjaljfladjflakfjalkfjlalsfjklafjlajfaljdflajdflakjlkfdjalkjf"} preco={"R$"+15.5} /><CardProduto src={logo} nome={"Raçao para cachorro aldfjalsjflajdflakjdflajalfjaljfladjflakfjalkfjlalsfjklafjlajfaljdflajdflakjlkfdjalkjf"} preco={"R$"+15.5} /><CardProduto src={logo} nome={"Raçao para cachorro aldfjalsjflajdflakjdflajalfjaljfladjflakfjalkfjlalsfjklafjlajfaljdflajdflakjlkfdjalkjf"} preco={"R$"+15.5} />
           <CardProduto src={logo} nome={"Raçao para cachorro aldfjalsjflajdflakjdflajalfjaljfladjflakfjalkfjlalsfjklafjlajfaljdflajdflakjlkfdjalkjf"} preco={"R$"+15.5} /><CardProduto src={logo} nome={"Raçao para cachorro aldfjalsjflajdflakjdflajalfjaljfladjflakfjalkfjlalsfjklafjlajfaljdflajdflakjlkfdjalkjf"} preco={"R$"+15.5} /><CardProduto src={logo} nome={"Raçao para cachorro aldfjalsjflajdflakjdflajalfjaljfladjflakfjalkfjlalsfjklafjlajfaljdflajdflakjlkfdjalkjf"} preco={"R$"+15.5} /><CardProduto src={logo} nome={"Raçao para cachorro aldfjalsjflajdflakjdflajalfjaljfladjflakfjalkfjlalsfjklafjlajfaljdflajdflakjlkfdjalkjf"} preco={"R$"+15.5} />
           <CardProduto src={logo} nome={"Raçao para cachorro aldfjalsjflajdflakjdflajalfjaljfladjflakfjalkfjlalsfjklafjlajfaljdflajdflakjlkfdjalkjf"} preco={"R$"+15.5} /><CardProduto src={logo} nome={"Raçao para cachorro aldfjalsjflajdflakjdflajalfjaljfladjflakfjalkfjlalsfjklafjlajfaljdflajdflakjlkfdjalkjf"} preco={"R$"+15.5} /><CardProduto src={logo} nome={"Raçao para cachorro aldfjalsjflajdflakjdflajalfjaljfladjflakfjalkfjlalsfjklafjlajfaljdflajdflakjlkfdjalkjf"} preco={"R$"+15.5} /><CardProduto src={logo} nome={"Raçao para cachorro aldfjalsjflajdflakjdflajalfjaljfladjflakfjalkfjlalsfjklafjlajfaljdflajdflakjlkfdjalkjf"} preco={"R$"+15.5} />
           <CardProduto src={logo} nome={"Raçao para cachorro aldfjalsjflajdflakjdflajalfjaljfladjflakfjalkfjlalsfjklafjlajfaljdflajdflakjlkfdjalkjf"} preco={"R$"+15.5} /><CardProduto src={logo} nome={"Raçao para cachorro aldfjalsjflajdflakjdflajalfjaljfladjflakfjalkfjlalsfjklafjlajfaljdflajdflakjlkfdjalkjf"} preco={"R$"+15.5} /><CardProduto src={logo} nome={"Raçao para cachorro aldfjalsjflajdflakjdflajalfjaljfladjflakfjalkfjlalsfjklafjlajfaljdflajdflakjlkfdjalkjf"} preco={"R$"+15.5} /><CardProduto src={logo} nome={"Raçao para cachorro aldfjalsjflajdflakjdflajalfjaljfladjflakfjalkfjlalsfjklafjlajfaljdflajdflakjlkfdjalkjf"} preco={"R$"+15.5} />
           <CardProduto src={logo} nome={"Raçao para cachorro aldfjalsjflajdflakjdflajalfjaljfladjflakfjalkfjlalsfjklafjlajfaljdflajdflakjlkfdjalkjf"} preco={"R$"+15.5} /><CardProduto src={logo} nome={"Raçao para cachorro aldfjalsjflajdflakjdflajalfjaljfladjflakfjalkfjlalsfjklafjlajfaljdflajdflakjlkfdjalkjf"} preco={"R$"+15.5} /><CardProduto src={logo} nome={"Raçao para cachorro aldfjalsjflajdflakjdflajalfjaljfladjflakfjalkfjlalsfjklafjlajfaljdflajdflakjlkfdjalkjf"} preco={"R$"+15.5} /><CardProduto src={logo} nome={"Raçao para cachorro aldfjalsjflajdflakjdflajalfjaljfladjflakfjalkfjlalsfjklafjlajfaljdflajdflakjlkfdjalkjf"} preco={"R$"+15.5} />
           <CardProduto src={logo} nome={"Raçao para cachorro aldfjalsjflajdflakjdflajalfjaljfladjflakfjalkfjlalsfjklafjlajfaljdflajdflakjlkfdjalkjf"} preco={"R$"+15.5} /><CardProduto src={logo} nome={"Raçao para cachorro aldfjalsjflajdflakjdflajalfjaljfladjflakfjalkfjlalsfjklafjlajfaljdflajdflakjlkfdjalkjf"} preco={"R$"+15.5} /><CardProduto src={logo} nome={"Raçao para cachorro aldfjalsjflajdflakjdflajalfjaljfladjflakfjalkfjlalsfjklafjlajfaljdflajdflakjlkfdjalkjf"} preco={"R$"+15.5} /><CardProduto src={logo} nome={"Raçao para cachorro aldfjalsjflajdflakjdflajalfjaljfladjflakfjalkfjlalsfjklafjlajfaljdflajdflakjlkfdjalkjf"} preco={"R$"+15.5} />
           <CardProduto src={logo} nome={"Raçao para cachorro aldfjalsjflajdflakjdflajalfjaljfladjflakfjalkfjlalsfjklafjlajfaljdflajdflakjlkfdjalkjf"} preco={"R$"+15.5} /><CardProduto src={logo} nome={"Raçao para cachorro aldfjalsjflajdflakjdflajalfjaljfladjflakfjalkfjlalsfjklafjlajfaljdflajdflakjlkfdjalkjf"} preco={"R$"+15.5} /><CardProduto src={logo} nome={"Raçao para cachorro aldfjalsjflajdflakjdflajalfjaljfladjflakfjalkfjlalsfjklafjlajfaljdflajdflakjlkfdjalkjf"} preco={"R$"+15.5} /><CardProduto src={logo} nome={"Raçao para cachorro aldfjalsjflajdflakjdflajalfjaljfladjflakfjalkfjlalsfjklafjlajfaljdflajdflakjlkfdjalkjf"} preco={"R$"+15.5} />
           
        </Section>
    )
}